apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: chatbot1-may7-2
  janus-idp.io/tekton: chatbot1-may7-2
  backstage.io/kubernetes-id: chatbot1-may7-2
  backstage.io/kubernetes-namespace: chatbot1-may7-2
  app.kubernetes.io/part-of: chatbot1-may7-2
resources:
  - application-dev.yaml