apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: chatbot1-may7-2
  janus-idp.io/tekton: chatbot1-may7-2
  backstage.io/kubernetes-id: chatbot1-may7-2
  backstage.io/kubernetes-namespace: chatbot1-may7-2
  app.kubernetes.io/part-of: chatbot1-may7-2
resources:
  - initialize-namespace/
  - pvc.yaml
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
  - rhoai/
